### ISSUE TITLE
Update instructions on deployment

### ISSUE THREAD

**Issue by carschno** [esciencecenter-digital-skills/workshop-template#161]
Step 5 in the section `Required information and customizing your workshop page` currently says:
 
> Once you commit this, the github action will rebuild the workshop website. The index.md file will point to the alternative workshop metadata markdown file, so that will be included in the workshop website.

This is not correct, the deploy workflow is only triggered
- manually
- on pull requests
- on releases

As defined in the `jekyll.yml` file:
```yaml
on:
  workflow_dispatch:
  release:
    types:
      - published
  pull_request:
    branches:
      - main
```
